In [2]:
import numpy as np

array = np.random.randn(5, 3)
array


array([[-0.56937243,  1.66985554,  1.16599991],
       [ 0.73926429,  0.65339118, -0.05079294],
       [ 0.58419395, -0.26611418,  0.88587194],
       [-0.22597502, -1.08137253,  1.21246743],
       [ 0.71406427,  0.58328153, -1.82360698]])

In [4]:
array.sort(1)
array

array([[-0.56937243,  1.16599991,  1.66985554],
       [-0.05079294,  0.65339118,  0.73926429],
       [-0.26611418,  0.58419395,  0.88587194],
       [-1.08137253, -0.22597502,  1.21246743],
       [-1.82360698,  0.58328153,  0.71406427]])

In [6]:
large_array = np.random.randn(1000)
large_array.sort()
large_array


array([-2.92924997e+00, -2.88464373e+00, -2.78533107e+00, -2.58568070e+00,
       -2.58017702e+00, -2.47197078e+00, -2.45588731e+00, -2.41883680e+00,
       -2.35196842e+00, -2.30817832e+00, -2.28094149e+00, -2.27553874e+00,
       -2.25948146e+00, -2.21231589e+00, -2.18910256e+00, -2.17451935e+00,
       -2.16914161e+00, -2.16134469e+00, -2.11683988e+00, -2.11019588e+00,
       -2.06173458e+00, -2.03866123e+00, -2.02337723e+00, -1.97821881e+00,
       -1.95352985e+00, -1.92418874e+00, -1.92303539e+00, -1.92182739e+00,
       -1.88574681e+00, -1.83099293e+00, -1.79684302e+00, -1.79349777e+00,
       -1.77343267e+00, -1.75818746e+00, -1.75145802e+00, -1.69117681e+00,
       -1.68937052e+00, -1.68563826e+00, -1.67039122e+00, -1.66159825e+00,
       -1.65495402e+00, -1.63660888e+00, -1.63329124e+00, -1.63159540e+00,
       -1.62117189e+00, -1.60449180e+00, -1.58967034e+00, -1.57961432e+00,
       -1.57908447e+00, -1.57724033e+00, -1.56362799e+00, -1.55752407e+00,
       -1.55712731e+00, -

To find the 5% quantile of this dataset, we use the formula "large_arr[int(0.05 * len(large_arr))] "

In [7]:
large_array[int(0.05 * len(large_array))] 


-1.5636279853790518

How to find the unique fields in a data set using np.unique

In [9]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

np.in1d, tests membership of the values in one array in another, returning a boolean array, as in it tells whether the given values are present in the array or not. intersect1d can be used to find out the common values, 

In [10]:
np.in1d(names, ["Kshitij", "Bob", "Will"])

array([ True, False,  True,  True,  True, False, False])